version: '3.2'

services:
  dev:
    image: 'docker.pkg.github.com/kimmy214/gitee-pages/dev:latest'
    build:
      context: .
      cache_from:
        - 'docker.pkg.github.com/kimmy214/gitee-pages/dev:latest'
    container_name: gitee_pages
    volumes:
      - ${PWD}:/repo
    stdin_open: true
    tty: true
    command:
      - bash
